require:
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-rake
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Metrics:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# Recreated in Sagittarius/Migration/CreateTableWithTimestamps to account for timezones
Rails/CreateTableWithTimestamps:
  Enabled: false

# Prefer foreign keys on database layer
Rails/HasManyOrHasOneDependent:
  Enabled: false

# Disabled for now, I18N will follow later
Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

# aggregate_failures is defined with derived metadata for every spec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - spec/rubocop/**/*

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
