name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2.2'
          - '3.3.6'
          - '3.4.7'
        rails:
          - '~> 8.0.0'
          - '~> 8.1.0'

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install gems
        run: bundle install
      - name: Run the default task
        run: bin/rake
